package handlers
// Package handlers contains HTTP handlers for the API.


























































}	}		})			"Endpoint": endpoint,		tmpl.Execute(w, map[string]string{		w.Header().Set("Content-Type", "text/html; charset=utf-8")	return func(w http.ResponseWriter, r *http.Request) {	tmpl := template.Must(template.New("playground").Parse(playgroundTemplate))func PlaygroundHandler(endpoint string) http.HandlerFunc {// PlaygroundHandler returns the GraphQL playground.`</html></body>  </script>    );      document.getElementById('graphiql'),      React.createElement(GraphiQL, { fetcher: fetcher }),    ReactDOM.render(    });      }        'X-API-Key': 'dev-api-key-12345'      headers: {      url: '{{.Endpoint}}',    const fetcher = GraphiQL.createFetcher({  <script>  <script crossorigin src="https://unpkg.com/graphiql/graphiql.min.js"></script>  <script crossorigin src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></script>  <script crossorigin src="https://unpkg.com/react/umd/react.production.min.js"></script>  <div id="graphiql">Loading...</div><body></head>  </style>    }      height: 100vh;    #graphiql {    }      overflow: hidden;      width: 100%;      margin: 0;      height: 100%;    body {  <style>  <link rel="stylesheet" href="https://unpkg.com/graphiql/graphiql.min.css" />  <title>AI Aggregator - GraphQL Playground</title><head><html><!DOCTYPE html>const playgroundTemplate = `)	"net/http"	"html/template"import (package handlers
