package shared
// Package shared contains shared utilities and helpers.
package shared

import (






























































}	return defaultValue	}		}			return i		if i, err := strconv.Atoi(value); err == nil {	if value := os.Getenv(key); value != "" {func getEnvInt(key string, defaultValue int) int {}	return defaultValue	}		return value	if value := os.Getenv(key); value != "" {func getEnv(key, defaultValue string) string {}	}		MinioBucket:     getEnv("MINIO_BUCKET", "aiaggregator"),		MinioSecretKey:  getEnv("MINIO_SECRET_KEY", "minioadmin"),		MinioAccessKey:  getEnv("MINIO_ACCESS_KEY", "minioadmin"),		MinioEndpoint:   getEnv("MINIO_ENDPOINT", "localhost:9000"),		AnthropicAPIKey: getEnv("ANTHROPIC_API_KEY", ""),		OpenAIAPIKey:    getEnv("OPENAI_API_KEY", ""),		JWTSecret:       getEnv("JWT_SECRET", "dev-secret-change-me"),		APIHost:         getEnv("API_HOST", "0.0.0.0"),		APIPort:         getEnv("API_PORT", "8080"),		RedisURL:        getEnv("REDIS_URL", "redis://localhost:6379"),		DatabaseURL:     getEnv("DATABASE_URL", "postgres://postgres:postgres@localhost:5432/aiaggregator?sslmode=disable"),	return &Config{func LoadConfig() *Config {// LoadConfig loads configuration from environment variables.}	MinioBucket    string	MinioSecretKey string	MinioAccessKey string	MinioEndpoint  string	// Storage	AnthropicAPIKey string	OpenAIAPIKey    string	// Providers	JWTSecret string	// Auth	APIHost string	APIPort string	// Server	RedisURL string	// Redis	DatabaseURL string	// Databasetype Config struct {// Config holds application configuration.)	"strconv"	"os"
