package server
































































































}	log.Info().Msg("Server exited properly")	}		log.Fatal().Err(err).Msg("Server forced to shutdown")	if err := srv.Shutdown(ctx); err != nil {	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)	log.Info().Msg("Shutting down server...")	<-done		Msg("Server is running")		Str("addr", srv.Addr).	log.Info().	}()		}			log.Fatal().Err(err).Msg("Failed to start server")		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {	go func() {	signal.Notify(done, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)	done := make(chan os.Signal, 1)	// Graceful shutdown	}		IdleTimeout:  60 * time.Second,		WriteTimeout: 60 * time.Second,		ReadTimeout:  15 * time.Second,		Handler:      r,		Addr:         fmt.Sprintf("%s:%s", cfg.APIHost, cfg.APIPort),	srv := &http.Server{	// Create server	r.Get("/playground", handlers.PlaygroundHandler("/graphql"))	r.Handle("/graphql", graphServer)	graphServer := graph.NewServer()	// GraphQL endpoint	r.Get("/health", handlers.HealthHandler)	// Health check	}))		MaxAge:           300,		AllowCredentials: true,		ExposedHeaders:   []string{"Link"},		AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-API-Key"},		AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},		AllowedOrigins:   []string{"http://localhost:3000", "http://localhost:*"},	r.Use(cors.Handler(cors.Options{	// CORS	r.Use(middleware.Timeout(60 * time.Second))	r.Use(middleware.Recoverer)	r.Use(middleware.Logger)	r.Use(middleware.RealIP)	r.Use(middleware.RequestID)	// Middleware	r := chi.NewRouter()	// Initialize router		Msg("Starting AI Aggregator API server")		Str("port", cfg.APIPort).	log.Info().	cfg := shared.LoadConfig()	log := shared.NewLogger("api")	_ = godotenv.Load()	// Load .env file if existsfunc main() {)	"github.com/ingvar/aiaggregator/packages/shared"	"github.com/ingvar/aiaggregator/apps/api/internal/handlers"	"github.com/ingvar/aiaggregator/apps/api/internal/graph"	"github.com/joho/godotenv"	"github.com/go-chi/cors"	"github.com/go-chi/chi/v5/middleware"	"github.com/go-chi/chi/v5"	"time"	"syscall"	"os/signal"	"os"	"net/http"	"fmt"	"context"import (package main// Package main is the entry point for the GraphQL API server.
