package adapters
// Package adapters contains infrastructure adapter implementations.
package adapters

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/ingvar/aiaggregator/packages/domain"
)



















































































































}	return tenants, nil	}		tenants = append(tenants, tenant)		}			return nil, err		if err != nil {		)			&tenant.CreatedAt, &tenant.UpdatedAt,			&tenant.ID, &tenant.Name, &tenant.APIKey, &tenant.Active,		err := rows.Scan(		tenant := &domain.Tenant{}	for rows.Next() {	var tenants []*domain.Tenant	defer rows.Close()	}		return nil, err	if err != nil {	rows, err := r.pool.Query(ctx, query, limit, offset)	`		LIMIT $1 OFFSET $2		ORDER BY created_at DESC		FROM tenants		SELECT id, name, api_key, active, created_at, updated_at	query := `func (r *PostgresTenantRepository) List(ctx context.Context, limit, offset int) ([]*domain.Tenant, error) {// List retrieves tenants with pagination.}	return err	_, err := r.pool.Exec(ctx, query, id)	query := `DELETE FROM tenants WHERE id = $1`func (r *PostgresTenantRepository) Delete(ctx context.Context, id uuid.UUID) error {// Delete removes a tenant from the database.}	return err	)		tenant.ID, tenant.Name, tenant.Active, tenant.UpdatedAt,	_, err := r.pool.Exec(ctx, query,	`		WHERE id = $1		UPDATE tenants SET name = $2, active = $3, updated_at = $4	query := `func (r *PostgresTenantRepository) Update(ctx context.Context, tenant *domain.Tenant) error {// Update updates an existing tenant in the database.}	return tenant, nil	}		return nil, err	if err != nil {	}		return nil, domain.ErrTenantNotFound	if err == pgx.ErrNoRows {	)		&tenant.CreatedAt, &tenant.UpdatedAt,		&tenant.ID, &tenant.Name, &tenant.APIKey, &tenant.Active,	err := row.Scan(	tenant := &domain.Tenant{}	row := r.pool.QueryRow(ctx, query, apiKey)	`		FROM tenants WHERE api_key = $1 AND active = true		SELECT id, name, api_key, active, created_at, updated_at	query := `func (r *PostgresTenantRepository) GetByAPIKey(ctx context.Context, apiKey string) (*domain.Tenant, error) {// GetByAPIKey retrieves a tenant by its API key.}	return tenant, nil	}		return nil, err	if err != nil {	}		return nil, domain.ErrTenantNotFound	if err == pgx.ErrNoRows {	)		&tenant.CreatedAt, &tenant.UpdatedAt,		&tenant.ID, &tenant.Name, &tenant.APIKey, &tenant.Active,	err := row.Scan(	tenant := &domain.Tenant{}	row := r.pool.QueryRow(ctx, query, id)	`		FROM tenants WHERE id = $1		SELECT id, name, api_key, active, created_at, updated_at	query := `func (r *PostgresTenantRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Tenant, error) {// GetByID retrieves a tenant by its ID.}	return err	)		tenant.CreatedAt, tenant.UpdatedAt,		tenant.ID, tenant.Name, tenant.APIKey, tenant.Active,	_, err := r.pool.Exec(ctx, query,	`		VALUES ($1, $2, $3, $4, $5, $6)		INSERT INTO tenants (id, name, api_key, active, created_at, updated_at)	query := `func (r *PostgresTenantRepository) Create(ctx context.Context, tenant *domain.Tenant) error {// Create inserts a new tenant into the database.}	return &PostgresTenantRepository{pool: pool}func NewPostgresTenantRepository(pool *pgxpool.Pool) *PostgresTenantRepository {// NewPostgresTenantRepository creates a new PostgreSQL tenant repository.}	pool *pgxpool.Pooltype PostgresTenantRepository struct {// PostgresTenantRepository implements TenantRepository using PostgreSQL.
