package usecases
// Package usecases contains application business logic and use case implementations.
package usecases




























































}	SelectProvider(ctx context.Context, jobType domain.JobType) (AIProvider, error)type ProviderSelector interface {// ProviderSelector selects the best available provider for a request.}	Cost     float64	Model    string	URL      stringtype ImageResponse struct {// ImageResponse represents an image generation response.}	Options map[string]interface{}	Size    string	Model   string	Prompt  string	JobID   uuid.UUIDtype ImageRequest struct {// ImageRequest represents an image generation request.}	Cost      float64	TokensOut int	TokensIn  int	Model     string	Content   stringtype CompletionResponse struct {// CompletionResponse represents a text completion response.}	Options   map[string]interface{}	MaxTokens int	Model     string	Prompt    string	JobID     uuid.UUIDtype CompletionRequest struct {// CompletionRequest represents a text completion request.}	IsAvailable(ctx context.Context) bool	// IsAvailable checks if the provider is currently available.	GenerateImage(ctx context.Context, request *ImageRequest) (*ImageResponse, error)	// GenerateImage generates an image from a prompt.	Complete(ctx context.Context, request *CompletionRequest) (*CompletionResponse, error)	// Complete performs a text completion request.	Type() domain.ProviderType	// Type returns the provider type.	Name() string	// Name returns the provider name.type AIProvider interface {// AIProvider defines the interface for AI provider drivers.)	"github.com/ingvar/aiaggregator/packages/domain"	"github.com/google/uuid"	"context"import (
