package usecases















































}	GetSummary(ctx context.Context, tenantID uuid.UUID) ([]*domain.UsageSummary, error)	GetByTenantID(ctx context.Context, tenantID uuid.UUID, limit, offset int) ([]*domain.Usage, error)	GetByJobID(ctx context.Context, jobID uuid.UUID) (*domain.Usage, error)	Create(ctx context.Context, usage *domain.Usage) errortype UsageRepository interface {// UsageRepository defines the interface for usage persistence.}	List(ctx context.Context) ([]*domain.Provider, error)	Delete(ctx context.Context, id uuid.UUID) error	Update(ctx context.Context, provider *domain.Provider) error	GetEnabled(ctx context.Context) ([]*domain.Provider, error)	GetByID(ctx context.Context, id uuid.UUID) (*domain.Provider, error)	Create(ctx context.Context, provider *domain.Provider) errortype ProviderRepository interface {// ProviderRepository defines the interface for provider persistence.}	List(ctx context.Context, limit, offset int) ([]*domain.Tenant, error)	Delete(ctx context.Context, id uuid.UUID) error	Update(ctx context.Context, tenant *domain.Tenant) error	GetByAPIKey(ctx context.Context, apiKey string) (*domain.Tenant, error)	GetByID(ctx context.Context, id uuid.UUID) (*domain.Tenant, error)	Create(ctx context.Context, tenant *domain.Tenant) errortype TenantRepository interface {// TenantRepository defines the interface for tenant persistence.}	Count(ctx context.Context, tenantID uuid.UUID) (int, error)	Delete(ctx context.Context, id uuid.UUID) error	Update(ctx context.Context, job *domain.Job) error	GetByTenantID(ctx context.Context, tenantID uuid.UUID, limit, offset int) ([]*domain.Job, error)	GetByID(ctx context.Context, id uuid.UUID) (*domain.Job, error)	Create(ctx context.Context, job *domain.Job) errortype JobRepository interface {// JobRepository defines the interface for job persistence.)	"github.com/ingvar/aiaggregator/packages/domain"	"github.com/google/uuid"	"context"import (package usecases// Package usecases contains application business logic and use case implementations.
