package providers
























































































}	p.delay = delayfunc (p *StubProvider) SetDelay(delay time.Duration) {// SetDelay sets the simulated processing delay.}	p.available = availablefunc (p *StubProvider) SetAvailable(available bool) {// SetAvailable sets the provider availability for testing.}	return p.availablefunc (p *StubProvider) IsAvailable(ctx context.Context) bool {// IsAvailable checks if the provider is available.}	}, nil		Cost:  0.02,		Model: "stub-image-v1",		URL:   "https://placeholder.example.com/generated-image.png",	return &usecases.ImageResponse{	}	case <-time.After(p.delay):		return nil, ctx.Err()	case <-ctx.Done():	select {func (p *StubProvider) GenerateImage(ctx context.Context, request *usecases.ImageRequest) (*usecases.ImageResponse, error) {// GenerateImage performs a mock image generation.}	}, nil		Cost:      float64(inputTokens+outputTokens) * 0.00001,		TokensOut: outputTokens,		TokensIn:  inputTokens,		Model:     "stub-model-v1",		Content:   fmt.Sprintf("This is a stub response for prompt: %s", request.Prompt[:min(50, len(request.Prompt))]),	return &usecases.CompletionResponse{	outputTokens := inputTokens * 2	inputTokens := len(request.Prompt) / 4	// Generate mock response	}	case <-time.After(p.delay):		return nil, ctx.Err()	case <-ctx.Done():	select {func (p *StubProvider) Complete(ctx context.Context, request *usecases.CompletionRequest) (*usecases.CompletionResponse, error) {// Complete performs a mock text completion.}	return domain.ProviderTypeLocalfunc (p *StubProvider) Type() domain.ProviderType {// Type returns the provider type.}	return p.namefunc (p *StubProvider) Name() string {// Name returns the provider name.}	}		delay:     100 * time.Millisecond,		available: true,		name:      name,	return &StubProvider{func NewStubProvider(name string) *StubProvider {// NewStubProvider creates a new stub provider.}	delay     time.Duration	available bool	name      stringtype StubProvider struct {// StubProvider is a mock AI provider for testing and development.)	"github.com/ingvar/aiaggregator/packages/usecases"	"github.com/ingvar/aiaggregator/packages/domain"	"time"	"fmt"	"context"import (package providers// Package providers contains AI provider implementations.
