// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobsByTenant = `-- name: CountJobsByTenant :one
SELECT COUNT(*) FROM jobs WHERE tenant_id = $1
`

func (q *Queries) CountJobsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (tenant_id, type, input, status)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, type, input, status, result, error, provider, tokens_in, tokens_out, cost, created_at, updated_at, started_at, finished_at
`

type CreateJobParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Type     string      `db:"type" json:"type"`
	Input    string      `db:"input" json:"input"`
	Status   string      `db:"status" json:"status"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.TenantID,
		arg.Type,
		arg.Input,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Input,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.Provider,
		&i.TokensIn,
		&i.TokensOut,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, tenant_id, type, input, status, result, error, provider, tokens_in, tokens_out, cost, created_at, updated_at, started_at, finished_at FROM jobs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Input,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.Provider,
		&i.TokensIn,
		&i.TokensOut,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, tenant_id, type, input, status, result, error, provider, tokens_in, tokens_out, cost, created_at, updated_at, started_at, finished_at FROM jobs
WHERE status = $1
ORDER BY created_at ASC
LIMIT $2
`

type ListJobsByStatusParams struct {
	Status string `db:"status" json:"status"`
	Limit  int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Input,
			&i.Status,
			&i.Result,
			&i.Error,
			&i.Provider,
			&i.TokensIn,
			&i.TokensOut,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByTenant = `-- name: ListJobsByTenant :many
SELECT id, tenant_id, type, input, status, result, error, provider, tokens_in, tokens_out, cost, created_at, updated_at, started_at, finished_at FROM jobs
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByTenantParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListJobsByTenant(ctx context.Context, arg ListJobsByTenantParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Input,
			&i.Status,
			&i.Result,
			&i.Error,
			&i.Provider,
			&i.TokensIn,
			&i.TokensOut,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET status = $2, result = $3, error = $4, provider = $5,
    tokens_in = $6, tokens_out = $7, cost = $8,
    started_at = $9, finished_at = $10, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, type, input, status, result, error, provider, tokens_in, tokens_out, cost, created_at, updated_at, started_at, finished_at
`

type UpdateJobParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Status     string             `db:"status" json:"status"`
	Result     pgtype.Text        `db:"result" json:"result"`
	Error      pgtype.Text        `db:"error" json:"error"`
	Provider   pgtype.Text        `db:"provider" json:"provider"`
	TokensIn   pgtype.Int4        `db:"tokens_in" json:"tokens_in"`
	TokensOut  pgtype.Int4        `db:"tokens_out" json:"tokens_out"`
	Cost       pgtype.Numeric     `db:"cost" json:"cost"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.Error,
		arg.Provider,
		arg.TokensIn,
		arg.TokensOut,
		arg.Cost,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Input,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.Provider,
		&i.TokensIn,
		&i.TokensOut,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
