// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Type       string             `db:"type" json:"type"`
	Input      string             `db:"input" json:"input"`
	Status     string             `db:"status" json:"status"`
	Result     pgtype.Text        `db:"result" json:"result"`
	Error      pgtype.Text        `db:"error" json:"error"`
	Provider   pgtype.Text        `db:"provider" json:"provider"`
	TokensIn   pgtype.Int4        `db:"tokens_in" json:"tokens_in"`
	TokensOut  pgtype.Int4        `db:"tokens_out" json:"tokens_out"`
	Cost       pgtype.Numeric     `db:"cost" json:"cost"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

type Provider struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Type      string             `db:"type" json:"type"`
	Endpoint  pgtype.Text        `db:"endpoint" json:"endpoint"`
	ApiKey    pgtype.Text        `db:"api_key" json:"api_key"`
	Model     pgtype.Text        `db:"model" json:"model"`
	Enabled   pgtype.Bool        `db:"enabled" json:"enabled"`
	Priority  pgtype.Int4        `db:"priority" json:"priority"`
	Config    []byte             `db:"config" json:"config"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Tenant struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	ApiKey          string             `db:"api_key" json:"api_key"`
	Active          pgtype.Bool        `db:"active" json:"active"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DefaultProvider pgtype.Text        `db:"default_provider" json:"default_provider"`
	Settings        []byte             `db:"settings" json:"settings"`
}

type Usage struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	TenantID  pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	JobID     pgtype.UUID        `db:"job_id" json:"job_id"`
	Provider  string             `db:"provider" json:"provider"`
	Model     pgtype.Text        `db:"model" json:"model"`
	TokensIn  pgtype.Int4        `db:"tokens_in" json:"tokens_in"`
	TokensOut pgtype.Int4        `db:"tokens_out" json:"tokens_out"`
	Cost      pgtype.Numeric     `db:"cost" json:"cost"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
