// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pricing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPricing = `-- name: CreatePricing :one
INSERT INTO provider_pricing (provider, model, input_price_per_million, output_price_per_million, image_price, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider, model, input_price_per_million, output_price_per_million, image_price, is_default, created_at, updated_at
`

type CreatePricingParams struct {
	Provider              string         `db:"provider" json:"provider"`
	Model                 string         `db:"model" json:"model"`
	InputPricePerMillion  pgtype.Numeric `db:"input_price_per_million" json:"input_price_per_million"`
	OutputPricePerMillion pgtype.Numeric `db:"output_price_per_million" json:"output_price_per_million"`
	ImagePrice            pgtype.Numeric `db:"image_price" json:"image_price"`
	IsDefault             bool           `db:"is_default" json:"is_default"`
}

func (q *Queries) CreatePricing(ctx context.Context, arg CreatePricingParams) (ProviderPricing, error) {
	row := q.db.QueryRow(ctx, createPricing,
		arg.Provider,
		arg.Model,
		arg.InputPricePerMillion,
		arg.OutputPricePerMillion,
		arg.ImagePrice,
		arg.IsDefault,
	)
	var i ProviderPricing
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.InputPricePerMillion,
		&i.OutputPricePerMillion,
		&i.ImagePrice,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePricing = `-- name: DeletePricing :exec
DELETE FROM provider_pricing WHERE id = $1
`

func (q *Queries) DeletePricing(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePricing, id)
	return err
}

const getDefaultPricingByProvider = `-- name: GetDefaultPricingByProvider :one
SELECT id, provider, model, input_price_per_million, output_price_per_million, image_price, is_default, created_at, updated_at FROM provider_pricing 
WHERE provider = $1 AND is_default = true 
LIMIT 1
`

func (q *Queries) GetDefaultPricingByProvider(ctx context.Context, provider string) (ProviderPricing, error) {
	row := q.db.QueryRow(ctx, getDefaultPricingByProvider, provider)
	var i ProviderPricing
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.InputPricePerMillion,
		&i.OutputPricePerMillion,
		&i.ImagePrice,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPricing = `-- name: GetPricing :one
SELECT id, provider, model, input_price_per_million, output_price_per_million, image_price, is_default, created_at, updated_at FROM provider_pricing WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPricing(ctx context.Context, id pgtype.UUID) (ProviderPricing, error) {
	row := q.db.QueryRow(ctx, getPricing, id)
	var i ProviderPricing
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.InputPricePerMillion,
		&i.OutputPricePerMillion,
		&i.ImagePrice,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPricingByProviderModel = `-- name: GetPricingByProviderModel :one
SELECT id, provider, model, input_price_per_million, output_price_per_million, image_price, is_default, created_at, updated_at FROM provider_pricing 
WHERE provider = $1 AND model = $2 
LIMIT 1
`

type GetPricingByProviderModelParams struct {
	Provider string `db:"provider" json:"provider"`
	Model    string `db:"model" json:"model"`
}

func (q *Queries) GetPricingByProviderModel(ctx context.Context, arg GetPricingByProviderModelParams) (ProviderPricing, error) {
	row := q.db.QueryRow(ctx, getPricingByProviderModel, arg.Provider, arg.Model)
	var i ProviderPricing
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.InputPricePerMillion,
		&i.OutputPricePerMillion,
		&i.ImagePrice,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPricing = `-- name: ListPricing :many
SELECT id, provider, model, input_price_per_million, output_price_per_million, image_price, is_default, created_at, updated_at FROM provider_pricing 
ORDER BY provider, model
`

func (q *Queries) ListPricing(ctx context.Context) ([]ProviderPricing, error) {
	rows, err := q.db.Query(ctx, listPricing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderPricing{}
	for rows.Next() {
		var i ProviderPricing
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.InputPricePerMillion,
			&i.OutputPricePerMillion,
			&i.ImagePrice,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingByProvider = `-- name: ListPricingByProvider :many
SELECT id, provider, model, input_price_per_million, output_price_per_million, image_price, is_default, created_at, updated_at FROM provider_pricing 
WHERE provider = $1 
ORDER BY is_default DESC, model
`

func (q *Queries) ListPricingByProvider(ctx context.Context, provider string) ([]ProviderPricing, error) {
	rows, err := q.db.Query(ctx, listPricingByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderPricing{}
	for rows.Next() {
		var i ProviderPricing
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.InputPricePerMillion,
			&i.OutputPricePerMillion,
			&i.ImagePrice,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultPricing = `-- name: SetDefaultPricing :exec
UPDATE provider_pricing
SET is_default = (id = $2)
WHERE provider = $1
`

type SetDefaultPricingParams struct {
	Provider string      `db:"provider" json:"provider"`
	ID       pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) SetDefaultPricing(ctx context.Context, arg SetDefaultPricingParams) error {
	_, err := q.db.Exec(ctx, setDefaultPricing, arg.Provider, arg.ID)
	return err
}

const updatePricing = `-- name: UpdatePricing :one
UPDATE provider_pricing
SET 
    input_price_per_million = $2,
    output_price_per_million = $3,
    image_price = $4,
    is_default = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, provider, model, input_price_per_million, output_price_per_million, image_price, is_default, created_at, updated_at
`

type UpdatePricingParams struct {
	ID                    pgtype.UUID    `db:"id" json:"id"`
	InputPricePerMillion  pgtype.Numeric `db:"input_price_per_million" json:"input_price_per_million"`
	OutputPricePerMillion pgtype.Numeric `db:"output_price_per_million" json:"output_price_per_million"`
	ImagePrice            pgtype.Numeric `db:"image_price" json:"image_price"`
	IsDefault             bool           `db:"is_default" json:"is_default"`
}

func (q *Queries) UpdatePricing(ctx context.Context, arg UpdatePricingParams) (ProviderPricing, error) {
	row := q.db.QueryRow(ctx, updatePricing,
		arg.ID,
		arg.InputPricePerMillion,
		arg.OutputPricePerMillion,
		arg.ImagePrice,
		arg.IsDefault,
	)
	var i ProviderPricing
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.InputPricePerMillion,
		&i.OutputPricePerMillion,
		&i.ImagePrice,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
