// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (name, type, endpoint, api_key, model, enabled, priority, config)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, type, endpoint, api_key, model, enabled, priority, config, created_at, updated_at
`

type CreateProviderParams struct {
	Name     string      `db:"name" json:"name"`
	Type     string      `db:"type" json:"type"`
	Endpoint pgtype.Text `db:"endpoint" json:"endpoint"`
	ApiKey   pgtype.Text `db:"api_key" json:"api_key"`
	Model    pgtype.Text `db:"model" json:"model"`
	Enabled  pgtype.Bool `db:"enabled" json:"enabled"`
	Priority pgtype.Int4 `db:"priority" json:"priority"`
	Config   []byte      `db:"config" json:"config"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Type,
		arg.Endpoint,
		arg.ApiKey,
		arg.Model,
		arg.Enabled,
		arg.Priority,
		arg.Config,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Endpoint,
		&i.ApiKey,
		&i.Model,
		&i.Enabled,
		&i.Priority,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, type, endpoint, api_key, model, enabled, priority, config, created_at, updated_at FROM providers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProvider(ctx context.Context, id pgtype.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Endpoint,
		&i.ApiKey,
		&i.Model,
		&i.Enabled,
		&i.Priority,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
SELECT id, name, type, endpoint, api_key, model, enabled, priority, config, created_at, updated_at FROM providers WHERE name = $1 LIMIT 1
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByName, name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Endpoint,
		&i.ApiKey,
		&i.Model,
		&i.Enabled,
		&i.Priority,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledProviders = `-- name: ListEnabledProviders :many
SELECT id, name, type, endpoint, api_key, model, enabled, priority, config, created_at, updated_at FROM providers WHERE enabled = true ORDER BY priority DESC, name ASC
`

func (q *Queries) ListEnabledProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listEnabledProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Endpoint,
			&i.ApiKey,
			&i.Model,
			&i.Enabled,
			&i.Priority,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, type, endpoint, api_key, model, enabled, priority, config, created_at, updated_at FROM providers ORDER BY priority DESC, name ASC
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Endpoint,
			&i.ApiKey,
			&i.Model,
			&i.Enabled,
			&i.Priority,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET name = $2, type = $3, endpoint = $4, api_key = $5, model = $6,
    enabled = $7, priority = $8, config = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, name, type, endpoint, api_key, model, enabled, priority, config, created_at, updated_at
`

type UpdateProviderParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Name     string      `db:"name" json:"name"`
	Type     string      `db:"type" json:"type"`
	Endpoint pgtype.Text `db:"endpoint" json:"endpoint"`
	ApiKey   pgtype.Text `db:"api_key" json:"api_key"`
	Model    pgtype.Text `db:"model" json:"model"`
	Enabled  pgtype.Bool `db:"enabled" json:"enabled"`
	Priority pgtype.Int4 `db:"priority" json:"priority"`
	Config   []byte      `db:"config" json:"config"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Endpoint,
		arg.ApiKey,
		arg.Model,
		arg.Enabled,
		arg.Priority,
		arg.Config,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Endpoint,
		&i.ApiKey,
		&i.Model,
		&i.Enabled,
		&i.Priority,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
