// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountJobsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUsage(ctx context.Context, arg CreateUsageParams) (Usage, error)
	DeleteJob(ctx context.Context, id pgtype.UUID) error
	DeleteProvider(ctx context.Context, id pgtype.UUID) error
	DeleteTenant(ctx context.Context, id pgtype.UUID) error
	GetJob(ctx context.Context, id pgtype.UUID) (Job, error)
	GetProvider(ctx context.Context, id pgtype.UUID) (Provider, error)
	GetProviderByName(ctx context.Context, name string) (Provider, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantByAPIKey(ctx context.Context, apiKey string) (Tenant, error)
	GetUsage(ctx context.Context, id pgtype.UUID) (Usage, error)
	GetUsageByJobID(ctx context.Context, jobID pgtype.UUID) (Usage, error)
	GetUsageSummaryByProvider(ctx context.Context) ([]GetUsageSummaryByProviderRow, error)
	GetUsageSummaryByTenant(ctx context.Context, tenantID pgtype.UUID) ([]GetUsageSummaryByTenantRow, error)
	ListEnabledProviders(ctx context.Context) ([]Provider, error)
	ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error)
	ListJobsByTenant(ctx context.Context, arg ListJobsByTenantParams) ([]Job, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	ListUsageByTenant(ctx context.Context, arg ListUsageByTenantParams) ([]Usage, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
