// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, api_key, active)
VALUES ($1, $2, $3)
RETURNING id, name, api_key, active, created_at, updated_at, default_provider, settings
`

type CreateTenantParams struct {
	Name   string      `db:"name" json:"name"`
	ApiKey string      `db:"api_key" json:"api_key"`
	Active pgtype.Bool `db:"active" json:"active"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.ApiKey, arg.Active)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultProvider,
		&i.Settings,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, api_key, active, created_at, updated_at, default_provider, settings FROM tenants WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultProvider,
		&i.Settings,
	)
	return i, err
}

const getTenantByAPIKey = `-- name: GetTenantByAPIKey :one
SELECT id, name, api_key, active, created_at, updated_at, default_provider, settings FROM tenants WHERE api_key = $1 AND active = true LIMIT 1
`

func (q *Queries) GetTenantByAPIKey(ctx context.Context, apiKey string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByAPIKey, apiKey)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultProvider,
		&i.Settings,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, api_key, active, created_at, updated_at, default_provider, settings FROM tenants ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKey,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultProvider,
			&i.Settings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = $2, active = $3, default_provider = $4, settings = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, api_key, active, created_at, updated_at, default_provider, settings
`

type UpdateTenantParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Active          pgtype.Bool `db:"active" json:"active"`
	DefaultProvider pgtype.Text `db:"default_provider" json:"default_provider"`
	Settings        []byte      `db:"settings" json:"settings"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Active,
		arg.DefaultProvider,
		arg.Settings,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultProvider,
		&i.Settings,
	)
	return i, err
}
