// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthPayload struct {
	Success      bool         `json:"success"`
	SessionToken *string      `json:"sessionToken,omitempty"`
	Owner        *TenantOwner `json:"owner,omitempty"`
	Tenant       *Tenant      `json:"tenant,omitempty"`
	Error        *string      `json:"error,omitempty"`
}

type ChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type CreateJobInput struct {
	Type  JobType `json:"type"`
	Input string  `json:"input"`
}

type CreateOwnerInput struct {
	Email    string    `json:"email"`
	Password string    `json:"password"`
	Name     string    `json:"name"`
	Role     OwnerRole `json:"role"`
}

type CreatePricingInput struct {
	Provider              string   `json:"provider"`
	Model                 string   `json:"model"`
	InputPricePerMillion  float64  `json:"inputPricePerMillion"`
	OutputPricePerMillion float64  `json:"outputPricePerMillion"`
	ImagePrice            *float64 `json:"imagePrice,omitempty"`
	IsDefault             *bool    `json:"isDefault,omitempty"`
}

type Job struct {
	ID         string     `json:"id"`
	TenantID   string     `json:"tenantId"`
	Type       JobType    `json:"type"`
	Input      string     `json:"input"`
	Status     JobStatus  `json:"status"`
	Result     *string    `json:"result,omitempty"`
	Error      *string    `json:"error,omitempty"`
	Provider   *string    `json:"provider,omitempty"`
	TokensIn   int        `json:"tokensIn"`
	TokensOut  int        `json:"tokensOut"`
	Cost       float64    `json:"cost"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
	StartedAt  *time.Time `json:"startedAt,omitempty"`
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
}

type JobConnection struct {
	Edges    []*JobEdge `json:"edges"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type JobEdge struct {
	Node   *Job   `json:"node"`
	Cursor string `json:"cursor"`
}

type JobsFilter struct {
	Status *JobStatus `json:"status,omitempty"`
	Type   *JobType   `json:"type,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ModelInfo struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	MaxTokens   *int    `json:"maxTokens,omitempty"`
}

type Mutation struct {
}

type NotificationSettings struct {
	JobCompleted    bool `json:"jobCompleted"`
	JobFailed       bool `json:"jobFailed"`
	ProviderOffline bool `json:"providerOffline"`
	UsageThreshold  bool `json:"usageThreshold"`
	WeeklySummary   bool `json:"weeklySummary"`
	MarketingEmails bool `json:"marketingEmails"`
}

type NotificationSettingsInput struct {
	JobCompleted    *bool `json:"jobCompleted,omitempty"`
	JobFailed       *bool `json:"jobFailed,omitempty"`
	ProviderOffline *bool `json:"providerOffline,omitempty"`
	UsageThreshold  *bool `json:"usageThreshold,omitempty"`
	WeeklySummary   *bool `json:"weeklySummary,omitempty"`
	MarketingEmails *bool `json:"marketingEmails,omitempty"`
}

type PageInfo struct {
	TotalCount      int  `json:"totalCount"`
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
}

type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type Provider struct {
	ID       string       `json:"id"`
	Name     string       `json:"name"`
	Type     ProviderType `json:"type"`
	Enabled  bool         `json:"enabled"`
	Priority int          `json:"priority"`
}

type ProviderPricing struct {
	ID                    string    `json:"id"`
	Provider              string    `json:"provider"`
	Model                 string    `json:"model"`
	InputPricePerMillion  float64   `json:"inputPricePerMillion"`
	OutputPricePerMillion float64   `json:"outputPricePerMillion"`
	ImagePrice            *float64  `json:"imagePrice,omitempty"`
	IsDefault             bool      `json:"isDefault"`
	CreatedAt             time.Time `json:"createdAt"`
	UpdatedAt             time.Time `json:"updatedAt"`
}

type Query struct {
}

type RegisterInput struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	Name       string `json:"name"`
	TenantName string `json:"tenantName"`
}

type Session struct {
	ID        string    `json:"id"`
	UserAgent *string   `json:"userAgent,omitempty"`
	IPAddress *string   `json:"ipAddress,omitempty"`
	ExpiresAt time.Time `json:"expiresAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type Subscription struct {
}

type Tenant struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Active          bool            `json:"active"`
	DefaultProvider *string         `json:"defaultProvider,omitempty"`
	Settings        *TenantSettings `json:"settings,omitempty"`
	CreatedAt       time.Time       `json:"createdAt"`
	UpdatedAt       time.Time       `json:"updatedAt"`
}

type TenantOwner struct {
	ID            string     `json:"id"`
	TenantID      string     `json:"tenantId"`
	Email         string     `json:"email"`
	Name          string     `json:"name"`
	Role          OwnerRole  `json:"role"`
	Active        bool       `json:"active"`
	EmailVerified bool       `json:"emailVerified"`
	LastLoginAt   *time.Time `json:"lastLoginAt,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
}

type TenantSettings struct {
	DarkMode      bool                  `json:"darkMode"`
	Notifications *NotificationSettings `json:"notifications"`
}

type TenantSettingsInput struct {
	DarkMode      *bool                      `json:"darkMode,omitempty"`
	Notifications *NotificationSettingsInput `json:"notifications,omitempty"`
}

type UpdateOwnerInput struct {
	Name   *string    `json:"name,omitempty"`
	Role   *OwnerRole `json:"role,omitempty"`
	Active *bool      `json:"active,omitempty"`
}

type UpdatePricingInput struct {
	ID                    string   `json:"id"`
	InputPricePerMillion  float64  `json:"inputPricePerMillion"`
	OutputPricePerMillion float64  `json:"outputPricePerMillion"`
	ImagePrice            *float64 `json:"imagePrice,omitempty"`
	IsDefault             *bool    `json:"isDefault,omitempty"`
}

type UpdateTenantInput struct {
	Name            *string              `json:"name,omitempty"`
	DefaultProvider *string              `json:"defaultProvider,omitempty"`
	Settings        *TenantSettingsInput `json:"settings,omitempty"`
}

type Usage struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenantId"`
	JobID     string    `json:"jobId"`
	Provider  string    `json:"provider"`
	Model     *string   `json:"model,omitempty"`
	TokensIn  int       `json:"tokensIn"`
	TokensOut int       `json:"tokensOut"`
	Cost      float64   `json:"cost"`
	CreatedAt time.Time `json:"createdAt"`
}

type UsageSummary struct {
	Provider       string  `json:"provider"`
	TotalTokensIn  int     `json:"totalTokensIn"`
	TotalTokensOut int     `json:"totalTokensOut"`
	TotalCost      float64 `json:"totalCost"`
	JobCount       int     `json:"jobCount"`
}

type JobStatus string

const (
	JobStatusPending    JobStatus = "PENDING"
	JobStatusProcessing JobStatus = "PROCESSING"
	JobStatusCompleted  JobStatus = "COMPLETED"
	JobStatusFailed     JobStatus = "FAILED"
)

var AllJobStatus = []JobStatus{
	JobStatusPending,
	JobStatusProcessing,
	JobStatusCompleted,
	JobStatusFailed,
}

func (e JobStatus) IsValid() bool {
	switch e {
	case JobStatusPending, JobStatusProcessing, JobStatusCompleted, JobStatusFailed:
		return true
	}
	return false
}

func (e JobStatus) String() string {
	return string(e)
}

func (e *JobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStatus", str)
	}
	return nil
}

func (e JobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobType string

const (
	JobTypeText  JobType = "TEXT"
	JobTypeImage JobType = "IMAGE"
)

var AllJobType = []JobType{
	JobTypeText,
	JobTypeImage,
}

func (e JobType) IsValid() bool {
	switch e {
	case JobTypeText, JobTypeImage:
		return true
	}
	return false
}

func (e JobType) String() string {
	return string(e)
}

func (e *JobType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobType", str)
	}
	return nil
}

func (e JobType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OwnerRole string

const (
	OwnerRoleOwner  OwnerRole = "OWNER"
	OwnerRoleAdmin  OwnerRole = "ADMIN"
	OwnerRoleMember OwnerRole = "MEMBER"
)

var AllOwnerRole = []OwnerRole{
	OwnerRoleOwner,
	OwnerRoleAdmin,
	OwnerRoleMember,
}

func (e OwnerRole) IsValid() bool {
	switch e {
	case OwnerRoleOwner, OwnerRoleAdmin, OwnerRoleMember:
		return true
	}
	return false
}

func (e OwnerRole) String() string {
	return string(e)
}

func (e *OwnerRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OwnerRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OwnerRole", str)
	}
	return nil
}

func (e OwnerRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OwnerRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OwnerRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProviderType string

const (
	ProviderTypeOpenai ProviderType = "OPENAI"
	ProviderTypeClaude ProviderType = "CLAUDE"
	ProviderTypeLocal  ProviderType = "LOCAL"
	ProviderTypeOllama ProviderType = "OLLAMA"
)

var AllProviderType = []ProviderType{
	ProviderTypeOpenai,
	ProviderTypeClaude,
	ProviderTypeLocal,
	ProviderTypeOllama,
}

func (e ProviderType) IsValid() bool {
	switch e {
	case ProviderTypeOpenai, ProviderTypeClaude, ProviderTypeLocal, ProviderTypeOllama:
		return true
	}
	return false
}

func (e ProviderType) String() string {
	return string(e)
}

func (e *ProviderType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProviderType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProviderType", str)
	}
	return nil
}

func (e ProviderType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProviderType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProviderType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
